name: Github Action for Application 1
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install Application\ 1
      - name: Run tests
        run: npm run test Application\ 1
