name: Artifact
on:
  push:
    branches:
      - artifact
jobs:
  CreateAndUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact
        run: echo $JSON >> test.json
        env:
          JSON: ${{ toJSON(github) }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: json
          path: test.json
  Download:
    needs: CreateAndUpload
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: json
      - name: Print filesystem
        run: ls -la
