name: Cache
on:
  push:
    branches:
      - caching
jobs:
  Run1:
    runs-on: ubuntu-latest
    steps:
      - name: Load code
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pip3 install poetry
      - name: Caching dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs/application_4-aR5EQOGT-py3.10/
          key: key-${{ hashFiles('**/pyproject.toml') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --directory=Application\ 4/
      - name: Run python script
        run: |
          poetry run python main.py run1 --directory=Application\ 4/
  Run2:
    needs: Run1
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install poetry
        run: pip3 install poetry
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs/application_4-aR5EQOGT-py3.10/
          key: key-${{ hashFiles('**/pyproject.toml') }}
      - name: Install dependencies
        if: steps.cache.outpus.cache-hit != 'true'
        run: poetry install --directory=Application\ 4/
      - name: Run python script
        run: poetry run python main.py run2 --directory=Application\ 4/
