name: Choice
on:
  push:
jobs:
  Job0:
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: exit 1
  Job1:
    needs: Job0
    runs-on: ubuntu-latest
    steps:
    - name: Testing choice
      run: echo $CHOICE
      env:
        CHOICE: ${{ github.ref == 'refs/heads/main' }}
