name: Testing Conditional Statements
on:
  workflow_dispatch:
jobs:
  TestCondition:
    runs-on: ubuntu-latest
    steps:
    - name: Pre-requisites
      run: |
        echo "ENV=staging" >> $GITHUB_ENV
    - if: env.ENV == 'staging'
      run: echo "staging"
    - if: env.ENV != 'staging'
      run: echo "not staging"
