name: Testing cron job

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        default: 'staging'
        options: ['staging', 'production']

jobs:
  Testing:
    env:
      ENVIRONMENT: ${{ github.event.inputs.envrionment || 'production' }}
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        if: env.ENVIRONMENT == 'production'
        run: |
          echo "$ENVIRONMENT"
