name: Testing Environment Variables

on:
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "TEST=test" > $GITHUB_ENV
    - run: bash test.sh
