name: Issues Actions
on:
  issue_comment:
jobs:
  Display:
    runs-on: ubuntu-latest
    steps:
      - name: Display issues number
        run: |
          echo Issues number $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}"
