name: Output
on:
  push:
    branches:
      - output
jobs:
  CreateAndStore:
    runs-on: ubuntu-latest
    outputs:
      rich_output: ${{ steps.store_output_step.output.value}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip3 install rich
      - name: Store ouptut
        id: store_output_step
        run: python3 test.py
  ExtractAndDisplay:
    needs: CreateAndStore
    runs-on: ubuntu-latest
    steps:
      - name: Extract output
        run: echo $OUTPUT
        env:
          OUTPUT: ${{ needs.CreateAndStore.outputs.rich_output }}
