name: Output
on:
  push:
    branches:
      - output
jobs:
  CreateAndStore:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run python code
        run: python3 test.py
