name: Testing pull request trigger
on:
  push:
    branches:
    - 'main'
jobs:
  yourJobName:
    name: Cool Job
    runs-on: ubuntu-latest
    steps:
      - name: Get region
        run: |
          ENVIRONMENT_REGION_MAP=$(cat <<END
          {
            "staging": "us-east-2", 
            "production": "us-east-1"
          }
          END
          )
          REGION=$(echo $ENVIRONMENT_REGION_MAP | jq -r 'to_entries[] | select(.key=="${{ env.environment }}") | .value')
          echo "REGION=$REGION" >> $GITHUB_ENV
      - name: Echo Selected value
        run: echo $TARGET_VAR
        env:
          TARGET_VAR: ${{ env.REGION }}
