name: Testing pull request trigger
on:
  push:
    branches:
    - 'test/**'
  workflow_dispatch:
jobs:
  GetBranch:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
      REGION: ${{ github.ref_name == "test/github-actions" && "us-east-1" || "us-east-2" }}
    steps:
    - run : echo "branch=${BRANCH##*/}}"
    - uses: hashicorp/setup-terraform@v2
    - run : terraform --version
    - run : echo "${REGION}"
    
