name: Testing pull request trigger
on:
  push:
    branches:
    - 'test/**'
  workflow_dispatch:
jobs:
  GetBranch:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
    steps:
    - run : echo "branch=${BRANCH##*/}}"
    - uses: hashicorp/setup-terraform@v2
    - run : terraform --version
    - run : echo ${{ fromJson('{32: "32", 64: "64"}')[32] }}
