name: Testing pull request trigger
on:
  push:
    branches:
    - 'test/**'
jobs:
  GetBranch:
    runs-on: ubuntu-latest
    steps:
    - run : echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
