name: Automating deployment on Amazon Web Services

on:
  push:
    branches:
    - 'test/**'
  workflow_dispatch:
jobs:
  Deploy_Code:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
      REGION: ${{ github.ref_name == 'test/github-actions' && 'us' || 'uk' }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - run: ls -la
      - name: Get Environment
        run: |
          BRANCH_ENVIRONMENT_MAP=$(cat <<END
          {
            "orchestrator-oob": "staging",
            "main": "production"
          }
          END
          )
          ENVIRONMENT=$(echo $BRANCH_ENVIRONMENT_MAP | jq -r 'to_entries[] | select(.key=="${{ github.ref_name }}") | .value')
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
      - name: Get region
        run: |
          ENVIRONMENT_REGION_MAP=$(cat <<END
          {
            "staging": "us-east-2",
            "production": "us-east-1"
          }
          END
          )
          REGION=$(echo $ENVIRONMENT_REGION_MAP | jq -r 'to_entries[] | select(.key=="${{ env.ENVIRONMENT }}") | .value')
          echo "REGION=$REGION" >> $GITHUB_ENV
      - run: echo ${{ env.REGION }} ${{ env.ENVIRONMENT }}
      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ""
          aws-region: "${{ env.REGION }}"
      - name: Run bash script
        run: |
          cd scripts
          bash build.sh apply "${{ env.ENVIRONMENT }}" --ignore-checksum
