name: Testing pull request trigger
on:
  push:
    branches:
    - 'main'
jobs:
  GetBranch:
    runs-on: ubuntu-latest
    steps:
    - run : echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
    - run : echo "region=${fromJson('{"staging":"us-eas-1", "production":"us-east-2"}')["staging"]}"
