name: Testing pull request trigger
on:
  push:
    branches:
    - 'main'
jobs:
  yourJobName:
    name: Cool Job
    runs-on: ubuntu-latest
    steps:
      - name: Get Environment
        run: |
          BRANCH_ENVIRONMENT_MAP=$(cat <<END
          {
            "staging": "staging", 
            "main": "production"
          }
          END
          )
          ENVIRONMENT=$(echo $BRANCH_ENVIRONMENT_MAP | jq -r 'to_entries[] | select(.key=="${{ github.ref_name }}") | .value')
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV 
      - name: Get region
        run: |
          ENVIRONMENT_REGION_MAP=$(cat <<END
          {
            "staging": "us-east-2", 
            "production": "us-east-1"
          }
          END
          )
          REGION=$(echo $ENVIRONMENT_REGION_MAP | jq -r 'to_entries[] | select(.key=="${{ env.ENVIRONMENT }}") | .value')
          echo "REGION=$REGION" >> $GITHUB_ENV
      - name: Echo Selected value
        run: echo $REGION $ENVIRONMENT
        env:
          REGION: ${{ env.REGION }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
