name: Testing pull request trigger
on:
  push:
    branches:
    - 'main'
jobs:
  yourJobName:
    name: Cool Job
    runs-on: ubuntu-latest
    steps:
      - name: Get Machine Arc 
        run: |
          MACHINE_ARC_MAP=$(cat <<END
          {
            32: "i386", 
            64: "x86_64",
            999: ${{ secrets.SECRET_ARC }}
          }
          END
          )
          TARGET_ARC=$(echo $MACHINE_ARC_MAP | jq -r 'to_entries[] | select(.key=="${{ github.event.inputs.machine_architecture }}") | .value')
          echo "TARGET_ARC=$TARGET_ARC" >> $GITHUB_ENV
      
      - name: Echo Selected value
        run: |
          echo ${env.TARGET_VAR}
