name: Testing pull request trigger
on:
  push:
    branches:
    - 'test/**'
jobs:
  GetBranch:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
    steps:
    - run : echo "branch=${BRANCH##*/}}"
