name: Python Script Output
on:
  push:
    branches:
      - output
jobs:
  RunAndSaveOutput:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.save_output.output.value }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip3 install art
      - name: Run and save output
        id: save_output
        run: |
          echo "value=$(python3 test.py)" >> $GITHUB_OUTPUT
  ReadAndDisplay:
    needs: RunAndSaveOutput
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: |
          echo "$VALUE"
        env:
          VALUE: ${{ needs.RunAndSaveOutput.outputs.value }}
