name: Secret
on:
  push:
    branches:
      - secret
jobs:
  Extract:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets
        if: secerts.USERNAME == 'user'
        run: echo "same"
