name: Secret
on:
  push:
    branches:
      - secret
jobs:
  Extract:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets
        run: |
          echo '${{ secrets.USERNAME }}'
          echo '${{ secrets.PASSWORD }}'
          echo '${{ secrets.DATABASE }}'
