name: Cron Job to Mirror Chainguard Images


on:
  workflow_dispatch:
  push:

  schedule:
    - cron: 0 */6 * * *

jobs:
  Mirror-Images:
    runs-on: ubuntu-latest
    steps:
      - name: Install regclient
        run: |
          sudo apt install curl
          curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >regctl
          chmod 755 regctl

      - name: Mirror Python Images
        run: |
          version=$(docker run --rm cgr.dev/chainguard/python:latest --version | grep -oP "[0-9]+\.[0-9]+\.[0-9]+")
          IFS="." read -r -a parts <<< $version
          versions=()
          current=""
          for value in ${parts[@]}; do [[ -z $current ]] && current=$value || current+=".$value" ; versions=(${versions[@]} "$current"); done
          echo ${versions[@]}
