name: Testing Functions

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - run: |
          test() { echo "hello"; }
          test

      - run: test
