name: Testing reusable workflow

on:
  push: 
    branches:
    - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ././github/workflows/reusable_workflow.yml
        
