name: Testing Concurrency 1

on:
  push:
    branches:
    - main

concurrency:
  group: "testing-concurrency"
  cancel-in-progress: false

jobs:
  Print:
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello"
